export default {

    "noteInput": () => import("./note.vue"),
    "spacerInput": () => import("./spacer.vue"),
    "emailInput": () => import("./email.vue"),
    "passwordInput": () => import("./password.vue"),
    "textInput": () => import("./text.vue"),
    "switchInput": () => import("./switch.vue"),
    "buttonInput": () => import("./button.vue"),
    "checkboxInput": () => import("./checkbox.vue"),
    "textareaInput": () => import("./textarea.vue"),
    "selectInput": () => import("./select.vue"),
    "iconInput": () => import("./icon.vue"),
    "avatarInput": () => import("./avatar.vue"),
    "refInput": () => import("./ref.vue"),
    "colorInput": () => import("./color.vue"),
    "menuInput": () => import("./menu.vue"),
    "submitInput": () => import("./submit.vue"),
    "htmlInput": () => import("./html.vue"),
    "daterangeInput": () => import("./date-range.vue"),
    "dateInput": () => import("./date.vue"),
    "timelineInput": () => import("./timeline.vue"),
    "editorInput":  () => import("./editor.vue"),
    "fileInput":  () => import("./file.vue"), 
    "chartInput":  () => import("./chart.vue"),
    "multiple-choiceInput":  () => import("./multiple-choice.vue"),
    "one-of-manyInput":  () => import("./multiple-choice.vue"),
    "checkboxesInput":  () => import("./checkboxes.vue"),
    "many-of-manyInput":  () => import("./checkboxes.vue"),
    "ratesInput":  () => import("./rates.vue"),
             
}
